import numpy as np
import torch
import torch.nn as nn
from cvxopt import matrix, solvers


# Barrier function model
def build_barrier(action_size):
    P = matrix(np.diag([1.0, 1e16]), tc="d")
    q = matrix(np.zeros(action_size + 1))
    H1 = np.array([1, 0.01])
    H2 = np.array([1, -0.01])
    H3 = np.array([-1, 0.01])
    H4 = np.array([-1, -0.01])
    F = 1
    return P, q, H1, H2, H3, H4, F


# Get compensatory action based on barrier function
def control_barrier(
    u_rl, f, g, x, std, P, q, H1, H2, H3, H4, F, torque_bound, max_speed
):
    gamma_b = 0.5
    kd = 1.5

    # Set up QP to satisfy CBF
    G = np.array(
        [
            [
                -np.dot(H1, g),
                -np.dot(H2, g),
                -np.dot(H3, g),
                -np.dot(H4, g),
                1,
                -1,
                g[1],
                -g[1],
            ],
            [-1, -1, -1, -1, 0, 0, 0, 0],
        ]
    )
    G = np.transpose(G)
    h = np.array(
        [
            gamma_b * F
            + np.dot(H1, f)
            + np.dot(H1, g) * u_rl
            - (1 - gamma_b) * np.dot(H1, x)
            - kd * np.abs(np.dot(H1, std)),
            gamma_b * F
            + np.dot(H2, f)
            + np.dot(H2, g) * u_rl
            - (1 - gamma_b) * np.dot(H2, x)
            - kd * np.abs(np.dot(H2, std)),
            gamma_b * F
            + np.dot(H3, f)
            + np.dot(H3, g) * u_rl
            - (1 - gamma_b) * np.dot(H3, x)
            - kd * np.abs(np.dot(H3, std)),
            gamma_b * F
            + np.dot(H4, f)
            + np.dot(H4, g) * u_rl
            - (1 - gamma_b) * np.dot(H4, x)
            - kd * np.abs(np.dot(H4, std)),
            -u_rl + torque_bound,
            u_rl + torque_bound,
            -f[1] - g[1] * u_rl + max_speed,
            f[1] + g[1] * u_rl + max_speed,
        ]
    )
    h = np.squeeze(h).astype(np.double)

    # Solve QP
    G = matrix(G, tc="d")
    h = matrix(h, tc="d")
    solvers.options["show_progress"] = False
    sol = solvers.qp(P, q, G, h)
    u_bar = sol["x"]

    if np.add(np.squeeze(u_rl), np.squeeze(u_bar[0])) - 0.001 >= torque_bound:
        u_bar[0] = torque_bound - u_rl
        print("Error in QP")
    elif np.add(np.squeeze(u_rl), np.squeeze(u_bar[0])) + 0.001 <= -torque_bound:
        u_bar[0] = -torque_bound - u_rl
        print("Error in QP")
    else:
        pass

    return np.expand_dims(np.array(u_bar[0]), 0)


# CBF Compensator Neural Network
class BarrierCompensator_nn(nn.Module):
    # Neural Network Architecture
    def __init__(self, obs_size, action_size):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(obs_size, 50),
            nn.ReLU(),
            nn.Linear(50, 40),
            nn.ReLU(),
            nn.Linear(40, action_size),
        )

    def forward(self, x):
        return self.net(x)

    # Control generated by the CBF Neural Network
    def get_action(self, obs):
        with torch.no_grad():
            u_BAR = self.forward(torch.FloatTensor(obs))
        return u_BAR.numpy()
